GET https://api.countapi.xyz/hit/1ccb732e-b55a-4404-ad3f-0f99c02fe44e

###

GET https://api.countapi.xyz/get/1ccb732e-b55a-4404-ad3f-0f99c02fe44e

###

GET https://api.countapi.xyz/info/1ccb732e-b55a-4404-ad3f-0f99c02fe44e